# -*- coding: utf-8 -*-
"""CME 小窝 · 演示数据（随代码一起部署，线上首次打开即看到每个功能的完整示例）。

为什么需要它：运行期数据写在 cme_*.json（.gitignore 已忽略）+ Upstash KV 里，
线上首次部署时两者都为空，页面就会是一片空白、看不到使用方式。
_cme_load() 在「云端 KV 无数据 且 本地文件不存在」时回退到这里，
因此线上页面永远能看到一份可交互的示例数据；用户一旦保存自己的数据，演示数据即被覆盖。
"""

CME_DEMO_SEED = {
    'snapshots':
    [   {   'symbol': 'GC',
            'price': 2912.4,
            'change': 0.43,
            'date': '2026-09-15',
            'time': '09:35',
            'note': '盘前快照：CPI 低于预期后的第二个交易日，金价站稳 2900 上方',
            'createdAt': 1789472120000},
        {   'symbol': 'DX',
            'price': 102.84,
            'change': -0.21,
            'date': '2026-09-15',
            'time': '09:35',
            'note': '美元指数走弱，与实际利率下行方向一致',
            'createdAt': 1789472119000},
        {   'symbol': '6E',
            'price': 1.0842,
            'change': 0.26,
            'date': '2026-09-15',
            'time': '09:35',
            'note': '欧元反弹，跟随美元走弱',
            'createdAt': 1789472118000},
        {   'symbol': 'NQ',
            'price': 20642.5,
            'change': 0.58,
            'date': '2026-09-15',
            'time': '09:35',
            'note': '折现率下行支撑高久期资产',
            'createdAt': 1789472117000},
        {   'symbol': 'GC',
            'price': 2898.7,
            'change': -0.12,
            'date': '2026-09-12',
            'time': '16:05',
            'note': 'CPI 公布前避险减仓，窄幅震荡',
            'createdAt': 1789200300000},
        {   'symbol': 'DX',
            'price': 103.06,
            'change': 0.18,
            'date': '2026-09-12',
            'time': '16:05',
            'note': 'CPI 前美元小幅走强',
            'createdAt': 1789200299000},
        {   'symbol': '6E',
            'price': 1.0813,
            'change': -0.19,
            'date': '2026-09-12',
            'time': '16:05',
            'note': '欧元承压，等待 CPI 指引',
            'createdAt': 1789200298000},
        {   'symbol': 'NQ',
            'price': 20523.8,
            'change': -0.34,
            'date': '2026-09-12',
            'time': '16:05',
            'note': '科技股在数据前回吐部分涨幅',
            'createdAt': 1789200297000},
        {   'symbol': 'GC',
            'price': 2903.1,
            'change': 0.62,
            'date': '2026-09-11',
            'time': '21:10',
            'note': '周线收强，实际利率预期降温',
            'createdAt': 1789080000000},
        {   'symbol': 'NQ',
            'price': 20594.3,
            'change': 0.91,
            'date': '2026-09-11',
            'time': '21:10',
            'note': '风险偏好回升，但成交未显著放大',
            'createdAt': 1789079999000}],
    'signals':
    [   {   'symbol': 'GC',
            'price': 2903.1,
            'bias': 'strong_bullish',
            'macro_score': 10,
            'confidence': 90,
            'range_low': 2874.069,
            'range_high': 2932.131,
            'drivers': ['美实际利率预期下行（CPI 走弱后市场加码降息预期）', '美元指数走弱，与利率方向一致', '避险情绪边际回升'],
            'invalidation': ['US 2Y 实际收益率重新上行', 'DXY 收复 103.5 并站稳', '美联储官员讲话转为明显鹰派'],
            'factors': [   {   'key': 'dxy',
                               'label': '美元指数 DXY',
                               'state': 'down',
                               'state_label': '走弱',
                               'score': 2,
                               'weight': 2},
                           {   'key': 'real_yield',
                               'label': '美实际利率',
                               'state': 'down',
                               'state_label': '下行',
                               'score': 2,
                               'weight': 2},
                           {   'key': 'fed_expect',
                               'label': '美联储预期',
                               'state': 'dovish',
                               'state_label': '鸽派',
                               'score': 1,
                               'weight': 1},
                           {   'key': 'risk_sentiment',
                               'label': '风险情绪',
                               'state': 'risk_off',
                               'state_label': '避险',
                               'score': 1,
                               'weight': 1},
                           {   'key': 'momentum',
                               'label': '动量',
                               'state': 'neutral',
                               'state_label': '中性',
                               'score': 0,
                               'weight': 1}],
            'model_version': 'macro_score_v1',
            'timestamp': 1789472040000},
        {   'symbol': '6E',
            'price': 1.0842,
            'bias': 'strong_bullish',
            'macro_score': 9,
            'confidence': 90,
            'range_low': 1.075528,
            'range_high': 1.092873,
            'drivers': ['美元走弱带动欧元被动走强', '美欧利差预期收窄', '欧元区数据边际企稳'],
            'invalidation': ['DXY 快速反弹', '欧元区 PMI 明显低于预期', 'ECB 转向更鸽派措辞'],
            'factors': [   {   'key': 'dxy',
                               'label': '美元指数 DXY',
                               'state': 'down',
                               'state_label': '走弱',
                               'score': 2,
                               'weight': 2},
                           {   'key': 'real_yield',
                               'label': '美实际利率',
                               'state': 'down',
                               'state_label': '下行',
                               'score': 2,
                               'weight': 2},
                           {   'key': 'fed_expect',
                               'label': '美联储预期',
                               'state': 'dovish',
                               'state_label': '鸽派',
                               'score': 1,
                               'weight': 1},
                           {   'key': 'risk_sentiment',
                               'label': '风险情绪',
                               'state': 'neutral',
                               'state_label': '中性',
                               'score': 0,
                               'weight': 1},
                           {   'key': 'momentum',
                               'label': '动量',
                               'state': 'neutral',
                               'state_label': '中性',
                               'score': 0,
                               'weight': 1}],
            'model_version': 'macro_score_v1',
            'timestamp': 1789471980000},
        {   'symbol': 'NQ',
            'price': 20594.3,
            'bias': 'bullish',
            'macro_score': 2,
            'confidence': 54,
            'range_low': 20285.3855,
            'range_high': 20903.2145,
            'drivers': ['折现率预期下行对高久期资产偏正面', '但风险偏好本身偏强，削弱避险溢价', '动量已偏超买，追高风险上升'],
            'invalidation': ['10Y 名义收益率快速回升', '科技权重股财报不及预期', '市场广度继续恶化'],
            'factors': [   {   'key': 'dxy',
                               'label': '美元指数 DXY',
                               'state': 'down',
                               'state_label': '走弱',
                               'score': 2,
                               'weight': 2},
                           {   'key': 'real_yield',
                               'label': '美实际利率',
                               'state': 'flat',
                               'state_label': '持平',
                               'score': 0,
                               'weight': 2},
                           {   'key': 'fed_expect',
                               'label': '美联储预期',
                               'state': 'neutral',
                               'state_label': '中性',
                               'score': 0,
                               'weight': 1},
                           {   'key': 'risk_sentiment',
                               'label': '风险情绪',
                               'state': 'risk_on',
                               'state_label': '风险偏好',
                               'score': -1,
                               'weight': 1},
                           {   'key': 'momentum',
                               'label': '动量',
                               'state': 'overbought',
                               'state_label': '超买',
                               'score': -1,
                               'weight': 1}],
            'model_version': 'macro_score_v1',
            'timestamp': 1789471920000}],
    'events':
    [   {   'id': '37fa61b80d2d',
            'event_type': 'CPI',
            'status': 'RELEASED',
            'country': 'US',
            'metric': 'Headline CPI YoY',
            'unit': '%',
            'sourceId': 'bloomberg-econ',
            'scheduled_at': '2026-09-18 20:30',
            'consensus': 2.7,
            'previous': 2.8,
            'importance': 'high',
            'source_url': '',
            'note': '原始 CPI 事件（待发布）',
            'created_at': 1789354490934,
            'actual': 2.4,
            'surprise': -0.3,
            'matched_scenario': 'COOL'},
        {   'id': 'a91c7d5e33b4',
            'event_type': 'NFP',
            'status': 'SCHEDULED',
            'country': 'US',
            'metric': 'Nonfarm Payrolls',
            'unit': 'K',
            'sourceId': 'bloomberg-econ',
            'scheduled_at': '2026-09-19 20:30',
            'consensus': 175,
            'previous': 142,
            'importance': 'high',
            'source_url': '',
            'note': '就业市场强弱将直接影响降息路径定价',
            'created_at': 1789354490935},
        {   'id': 'c4e0b17aa2d9',
            'event_type': 'FOMC',
            'status': 'SCHEDULED',
            'country': 'US',
            'metric': 'Fed Funds Target Rate',
            'unit': '%',
            'sourceId': 'federalreserve',
            'scheduled_at': '2026-09-24 02:00',
            'consensus': 4.25,
            'previous': 4.5,
            'importance': 'high',
            'source_url': 'https://www.federalreserve.gov/monetarypolicy.htm',
            'note': '点阵图与新闻发布会措辞是关键变量',
            'created_at': 1789354490936},
        {   'id': 'd0f3a9c821e5',
            'event_type': 'RETAIL_SALES',
            'status': 'RELEASED',
            'country': 'US',
            'metric': 'Retail Sales MoM',
            'unit': '%',
            'sourceId': 'bloomberg-econ',
            'scheduled_at': '2026-09-16 20:30',
            'consensus': 0.3,
            'previous': 0.5,
            'importance': 'medium',
            'source_url': '',
            'note': '消费韧性验证：强于预期会削弱降息叙事',
            'created_at': 1789354490937,
            'actual': 0.4,
            'surprise': 0.1,
            'matched_scenario': 'INLINE'}],
    'scenarios':
    [   {   'id': '5a69c5a4e6ad',
            'event_id': '37fa61b80d2d',
            'scenario_key': 'HOT',
            'scenario_name': 'HOT CPI',
            'tag': 'HAWKISH SURPRISE',
            'trigger_rule': 'surprise >= +0.2 percentage points',
            'transmission': [   'Inflation surprise ↑',
                                'Expected Fed easing ↓',
                                'US 2Y yield ↑',
                                'USD ↑ → EUR/USD ↓ / Gold ↓',
                                'High-duration equity valuation pressure ↑ → Nasdaq ↓'],
            'asset_impacts': [   {'asset': 'Gold', 'direction': 'down', 'label': '↓'},
                                 {'asset': 'DXY', 'direction': 'up', 'label': '↑'},
                                 {'asset': 'EUR/USD', 'direction': 'down', 'label': '↓'},
                                 {'asset': 'Nasdaq', 'direction': 'down', 'label': '↓'}],
            'counter_case': '市场可能已在 CPI 前定价鹰派，公布后出现 buy-the-news；或核心分项意外温和，削弱整体 surprise 的传导。',
            'invalidation': ['US 2Y 未上行', 'DXY 未走强', '核心 CPI 分项温和'],
            'triggered': False,
            'created_at': 1789385695473,
            'frozen_at': 1789472086556},
        {   'id': '54f1f24fdf5e',
            'event_id': '37fa61b80d2d',
            'scenario_key': 'INLINE',
            'scenario_name': 'INLINE',
            'tag': 'MIXED / LIMITED POLICY SURPRISE',
            'trigger_rule': 'surprise 落在 ±0.2 percentage points 之间',
            'transmission': [   'Macro event itself does not provide a sufficiently large '
                                'surprise.',
                                'Price action depends more on positioning, revisions, core CPI '
                                'components and existing market expectations.'],
            'asset_impacts': [   {'asset': 'Gold', 'direction': 'flat', 'label': '震荡'},
                                 {'asset': 'DXY', 'direction': 'flat', 'label': '震荡'},
                                 {'asset': 'EUR/USD', 'direction': 'flat', 'label': '震荡'},
                                 {'asset': 'Nasdaq', 'direction': 'flat', 'label': '震荡'}],
            'counter_case': '即使 headline inline，核心分项或季调修正仍可能主导即时反应。',
            'invalidation': ['US 2Y 出现 >10bp 方向性波动', 'DXY 突破近期区间'],
            'triggered': False,
            'created_at': 1789385695473,
            'frozen_at': 1789472086556},
        {   'id': '44ecf2af5d0c',
            'event_id': '37fa61b80d2d',
            'scenario_key': 'COOL',
            'scenario_name': 'COOL CPI',
            'tag': 'DOVISH SURPRISE',
            'trigger_rule': 'surprise <= -0.2 percentage points',
            'transmission': [   'Inflation surprise ↓',
                                'Expected Fed easing ↑',
                                'US 2Y yield ↓',
                                'USD ↓ → EUR/USD ↑ / Gold ↑',
                                'Discount rate ↓ → Nasdaq support ↑'],
            'asset_impacts': [   {'asset': 'Gold', 'direction': 'up', 'label': '↑'},
                                 {'asset': 'DXY', 'direction': 'down', 'label': '↓'},
                                 {'asset': 'EUR/USD', 'direction': 'up', 'label': '↑'},
                                 {'asset': 'Nasdaq', 'direction': 'up', 'label': '↑'}],
            'counter_case': '若通胀预期锚定牢固或核心分项仍强，市场可能对 headline 下修反应平淡。',
            'invalidation': ['US 2Y 未下行', 'DXY 未走弱'],
            'triggered': True,
            'created_at': 1789385695473,
            'frozen_at': 1789472086556}],
    'event_config':
    {   'mode': 'fixed_pp',
        'strongPositive': 0.2,
        'neutralUpper': 0.2,
        'neutralLower': -0.2,
        'strongNegative': -0.2,
        'zscore_std': None},
    'proposals':
    [   {   'id': '4a053a2aae6a',
            'created_at': 1789472086575,
            'updated_at': 1789472086617,
            'status': 'EXECUTED',
            'event_id': '37fa61b80d2d',
            'symbol': 'GC',
            'direction': 'long',
            'qty': 2,
            'origin': {   'event_id': '37fa61b80d2d',
                          'event_type': 'CPI',
                          'scenario': 'COOL',
                          'surprise': -0.3},
            'thesis': 'US CPI actual 2.4% vs consensus 2.7% (surprise -0.3pp) matched COOL. '
                      'Historical GC 1D path after 20 comparable events: median 0.54%, hit rate '
                      '65.0% (HIGHER evidence). Proposed long 2 contract(s) toward the historical '
                      'median path.',
            'five_questions': {   'why': 'After 20 comparable COOL events, GC 1D median 0.54% with '
                                         '65.0% hit rate (HIGHER evidence).',
                                  'why_now': 'Event released at 2026-09-18 20:30; entering the '
                                             'immediate post-release window before the move is '
                                             'fully priced.',
                                  'proves_wrong': 'US 2Y 未下行; DXY 未走弱',
                                  'max_loss': 'Stop out if loss exceeds the 1D Q25 range for 2 '
                                              'contract(s) plus commissions.',
                                  'reassess_at': 'Reassess at the 1D horizon mark; time-stop if '
                                                 'not working.'},
            'invalidation': {   'price_stop': 'Close if GC price moves against entry beyond the 1D '
                                              'Q25/Q75 range.',
                                'macro_invalidation': 'US 2Y 未下行; DXY 未走弱',
                                'time_stop': 'No overnight hold beyond the 1D reassessment '
                                             'window.'},
            'scenario_payoff': {   'symbol': 'GC',
                                   'code': 'GC',
                                   'name': 'Gold',
                                   'qty': 2,
                                   'direction': 'long',
                                   'tick_size': 0.1,
                                   'tick_value': 10.0,
                                   'reference_price': 2900.0,
                                   'commission_per_side': 2.5,
                                   'commission_total': 10.0,
                                   'bear': {'move_pct': -0.15, 'pnl': -880.0},
                                   'base': {'move_pct': 0.54, 'pnl': 3122.0},
                                   'bull': {'move_pct': 1.32, 'pnl': 7646.0}},
            'event_data': {   'actual': 2.4,
                              'consensus': 2.7,
                              'previous': 2.8,
                              'surprise': -0.3,
                              'scenario': 'COOL',
                              'hist_1d_median': 0.54,
                              'hist_1d_hit_rate': 65.0,
                              'hist_1d_n': 20},
            'risk_check': {   'result': 'PASS',
                              'checks': [   {   'name': 'Competition Status',
                                                'status': 'PASS',
                                                'message': 'Competition window is open.'},
                                            {   'name': 'Final-Day Liquidation',
                                                'status': 'PASS',
                                                'message': 'Not in final-day liquidation window.'},
                                            {   'name': 'Contract Expiry',
                                                'status': 'PASS',
                                                'message': 'Contract is not near expiry.'},
                                            {   'name': 'Margin Sufficiency',
                                                'status': 'PASS',
                                                'message': 'Margin after trade $18,000.00 within '
                                                           'net equity $1,000,000.00.'},
                                            {   'name': 'Worst-Case Loss',
                                                'status': 'PASS',
                                                'message': 'Bear-case loss $-880.00 (0.1% of net '
                                                           'equity) acceptable.'},
                                            {   'name': 'Daily Loss Buffer',
                                                'status': 'PASS',
                                                'message': '20.0% of daily loss buffer remaining.'},
                                            {   'name': 'Commission',
                                                'status': 'PASS',
                                                'message': 'Commissions $10.00 deducted in '
                                                           'scenario payoff.'},
                                            {   'name': 'Concentration',
                                                'status': 'PASS',
                                                'message': 'Concentration 0.0% within limit.'},
                                            {   'name': 'Correlated Exposure',
                                                'status': 'PASS',
                                                'message': 'No existing exposure in GC.'},
                                            {   'name': 'Contracts Today',
                                                'status': 'PASS',
                                                'message': 'Contracts today 2/10 after this '
                                                           'fill.'}],
                              'checked_at': 1789472086601},
            'post_trade_note': '',
            'review': None,
            'status_at': 1789472086617}],
    'positions':
    [   {   'symbol': 'GC',
            'qty': 2,
            'avg_price': 2900.0,
            'mark_price': 2912.4,
            'unrealized_pnl': 2480.0,
            'margin': 18000.0,
            'opened_at': '2026-09-15 08:35'},
        {   'symbol': 'NQ',
            'qty': 1,
            'avg_price': 20531.0,
            'mark_price': 20642.5,
            'unrealized_pnl': 2230.0,
            'margin': 19800.0,
            'opened_at': '2026-09-11 21:20'}],
    'journal':
    [   {   'id': 'cca6a11bc5b3',
            'trade_id': '',
            'proposal_id': '4a053a2aae6a',
            'symbol': 'GC',
            'direction': 'long',
            'entry_time': '2026-09-15 08:35',
            'exit_time': '',
            'entry_price': 2900.0,
            'exit_price': None,
            'qty': 2,
            'pnl': None,
            'thesis_result': 'pending',
            'error_tags': [],
            'review': ''},
        {   'id': 'b7d2f0c41a58',
            'trade_id': 'T-2026-0911-NQ-01',
            'proposal_id': '',
            'symbol': 'NQ',
            'direction': 'long',
            'entry_time': '2026-09-11 21:20',
            'exit_time': '2026-09-12 15:40',
            'entry_price': 20531.0,
            'exit_price': 20523.8,
            'qty': 1,
            'pnl': -36.0,
            'thesis_result': 'failed',
            'error_tags': ['过早入场', '数据前持仓'],
            'review': '在 CPI 公布前一天入场，属于典型的事件前暴露；虽然止损极小，但这是流程问题而不是结果问题。下次同类情形应先降仓或等确认。'},
        {   'id': '3f81c9a2de07',
            'trade_id': 'T-2026-0909-GC-01',
            'proposal_id': '',
            'symbol': 'GC',
            'direction': 'long',
            'entry_time': '2026-09-09 14:10',
            'exit_time': '2026-09-10 18:05',
            'entry_price': 2861.5,
            'exit_price': 2889.2,
            'qty': 2,
            'pnl': 5540.0,
            'thesis_result': 'worked',
            'error_tags': [],
            'review': '实际利率下行逻辑兑现，DXY 同步走弱提供交叉验证。唯一可改进处是加仓时机偏晚，错过第一波。'},
        {   'id': '91ac5b6e2f34',
            'trade_id': 'T-2026-0905-6E-01',
            'proposal_id': '',
            'symbol': '6E',
            'direction': 'short',
            'entry_time': '2026-09-05 10:25',
            'exit_time': '2026-09-05 20:10',
            'entry_price': 1.0902,
            'exit_price': 1.0921,
            'qty': 2,
            'pnl': -475.0,
            'thesis_result': 'failed',
            'error_tags': ['逆势', '无失效条件'],
            'review': '当时没有写下清晰的失效条件，导致止损是拍脑袋定出来的。补记：此后所有交易必须先填 invalidation 才能提交。'}],
    'risk_config':
    {   'account_equity': 1000000.0,
        'margin_pct': 10.0,
        'max_concentration_pct': 40.0,
        'max_contracts_per_day': 10,
        'max_daily_loss_pct': 20.0,
        'competition_open': True,
        'final_day_liquidation': False,
        'contract_near_expiry': False,
        'competition_timezone': 'America/Chicago',
        'trading_date': None,
        'risk_budget_pct': 0.3,
        'default_stop_pct': 0.5,
        'slippage_ticks': 1.0,
        'sizing_multipliers': {   'evidence': {   'HIGHER': 1.0,
                                                  'MEDIUM': 0.75,
                                                  'LOW': 0.5,
                                                  'VERY LOW': 0.25},
                                  'confirmation': {   'CONFIRMED': 1.0,
                                                      'PARTIALLY CONFIRMED': 0.75,
                                                      'MIXED': 0.5,
                                                      'DIVERGING': 0.25,
                                                      'NO TRADE': 0.0},
                                  'concentration_overlap': 0.75}},
}
